[package]
name = "ndn"
version = "0.0.1" # remember to update html_root_url
description = "[WIP] NDN - Named Data Networking in Rust"
documentation = "https://docs.rs/ndn"
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
homepage = "https://gitlab.com/imp/ndn-rs"
keywords = ["ndn", "named", "data", "networking"]
license = "Apache-2.0/MIT"
repository = "https://gitlab.com/imp/ndn-rs"
categories = ["network-programming"]
edition = "2021"

[badges]
travis-ci = { repository = "imp/ndn-rs" }
gitlab = { repository = "imp/ndn-rs" }

[dependencies]
bytes = "0.5"

[features]
pedantic = []
