[package]
name = "ndn-varnumber"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
bytes.workspace = true


[lints]
workspace = true
